
spring:
  datasource:

    select:
      jdbc-url: jdbc:mysql://10.1.1.120:3306/zx
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123

    update:
      jdbc-url: jdbc:mysql://localhost:3306/zx?characterEncoding=UTF-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
jpa:
    show-sql: true
    hibernate.ddl-auto: update
